### ISSUE TITLE
Example of multiple strips?

### ISSUE THREAD

**Issue by PanMan** [AaronLiddiment/LEDMatrix#12]
hi!
Is there an example how to use this with multiple strips, instead of a panel? I'd like to connect 8 ledstrips to an arduino (ESP) and show text on that... Thanks!

**Comment by AaronLiddiment** [comment]
All of my uses of this code was done with strips. You just link the strips at alternate ends in a zig zag way e.g.
11 12 13 14 15
10 09 08 07 06
01 02 03 04 05
Then just use HORIZONTAL_ZIGZAG_MATRIX as the Matrix type.

**Comment by PanMan** [comment]
Thanks!
I wanted to work with multiple strips, each connected to their own pin on the Arduino, as that is the setup I have already build (for other purpose, before I found this library).
I got that to work:
```
cLEDMatrix<-MATRIX_WIDTH, -MATRIX_HEIGHT, MATRIX_TYPE> leds;

  //And then adding all strips:
  FastLED.addLeds<LED_TYPE, 3,COLOR_ORDER>(leds[0], 0, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, 4,COLOR_ORDER>(leds[0], NUM_LEDS_PER_STRIP, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, 5,COLOR_ORDER>(leds[0], 2*NUM_LEDS_PER_STRIP, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, 6,COLOR_ORDER>(leds[0], 3*NUM_LEDS_PER_STRIP, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, 7,COLOR_ORDER>(leds[0], 4*NUM_LEDS_PER_STRIP, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, 8,COLOR_ORDER>(leds[0], 5*NUM_LEDS_PER_STRIP, NUM_LEDS_PER_STRIP).setCorrection(TypicalLEDStrip);
```

Works like a charm! You can close this issue. 
There is no 6 width font, right?
