### ISSUE TITLE
x-axis Shift methods not working for VERTICAL_ZIGZAG_MATRIX on ATMega328P

### ISSUE THREAD

**Issue by JaredTamana** [AaronLiddiment/LEDMatrix#14]
`config.h`:

```
// this file contains device-specific configurations and library imports

#ifndef config_h
#define config_h
#include <FastLED.h>
#include <LEDMatrix.h>
#include <Font12x16.h>
#include <Font16x24.h>
#include <FontMatrise.h>
#include <LEDText.h>

#define MATRIX_TILE_WIDTH   8 // width of matrix (not total display)
#define MATRIX_TILE_HEIGHT  -32 // height of matrix (negative due to flipped text, can use abs() to get positive)
#define MATRIX_TILE_TYPE VERTICAL_ZIGZAG_MATRIX
#define MATRIX_BOARD_CHIP WS2812B
#define MATRIX_TILE_H       1  // number of matrices arranged horizontally
#define MATRIX_TILE_V       1  // number of matrices arranged vertically
#define COLOR_ORDER GRB // hardware-dependent
#define LED_PIN 6 // pin where matrices are connected
#define NUM_LEDS MATRIX_TILE_WIDTH * abs(MATRIX_TILE_HEIGHT)

#define BRIGHTNESS 5 // brightness of LEDs
#endif
```

Sketch: 
```
// creating the matrix using LEDMatrix
// note that height and width are flipped in this example due to TILE_TYPE
cLEDMatrix <MATRIX_TILE_HEIGHT, MATRIX_TILE_WIDTH, MATRIX_TILE_TYPE> ledmatrix;
// creating a pointer to the matrix so FastLED can still operate
CRGB *leds = ledmatrix[0];

// Purpose: Draws a single LED, then delays. Good for particle effects.
// Accepts: int index of LED, long int hex code, int time to delay after drawing (optional)
// Returns: Nothing
void singleLED(int number, long int colour, int delaytime = 0) {
  leds[number] = colour;
  if (delaytime > 0) {
    FastLED.show();
    delay(delaytime);
  }
}

void setup() {
  // instantiate FastLED
  FastLED.addLeds<MATRIX_BOARD_CHIP, LED_PIN, COLOR_ORDER>(ledmatrix[0], ledmatrix.Size());
  FastLED.setBrightness(BRIGHTNESS);

  FastLED.clear();
  FastLED.show();
}

void loop() {

singleLED(248, CRGB::Red, 1000);
ledmatrix.ShiftDown();
FastLED.show();
delay(1000);
ledmatrix.ShiftRight();
FastLED.show();
delay(1000);
ledmatrix.ShiftUp();
FastLED.show();
delay(1000);
ledmatrix.ShiftLeft();
FastLED.show();
delay(1000);
}
```

Expected result: LED starts in top-left corner of matrix, shifts down, right, up, then left to rest back at its original position.

Actual result: LED shifts down correctly, but then stops moving altogether, even on subsequent loops

Probable cause: Looking at the code, I'm not seeing much discrepancy between the x-axis and y-axis methods.

- Is there some differentiation in `VZNWSL()` and `VZPWSL()` compared to `VZNHSD()` and `VZPHSD()` that I missed?
- Is my initialization of `cLEDMatrix` causing issues?
```
// note that height and width are flipped in this example due to TILE_TYPE
cLEDMatrix <MATRIX_TILE_HEIGHT, MATRIX_TILE_WIDTH, MATRIX_TILE_TYPE> ledmatrix;
```

**Comment by AaronLiddiment** [comment]
First off the board you are using only has 2k of ram which may be a problem. If I remember correctly due to buffering FastLED actually uses 6 bytes per CRGB element so 256 leds would be 1536 bytes. Not sure what the Arduino library & stack space overhead is but you may be running out of ram.

Secondly, I am confused by your flipping of Width/Height. The Matrix type is irrelevant as it just refers to how the leds are wired together. The use of negative values for width & height is how you then control where the 0,0 origin is. So if your first led is on the right you make Width negative and if your first led is at the top you make the height negative. Hope this makes it clearer.

**Comment by JaredTamana** [comment]
I'm actually hovering around 52% RAM usage with my current load according to the IDE, so I'm not sure that's the issue.

I got the negative index part, I figured that out a bit ago.

**Comment by AaronLiddiment** [comment]
The compiler will report static ram usage but will not know about any allocations that are made. As I said I am pretty sure that FastLED allocates a copy of the led array, I could be wrong though.  It would be good to try and allocate some memory using malloc() at the end of your setup routine and see if it returns a valid pointer. Then perhaps indicate this will the first led being turned on. Meanwhile I will take another look at the shift functions but as this is the most common type of array I have used I am pretty certain they are fine.

**Comment by JaredTamana** [comment]
You're right -- this is a memory issue. Thanks for the insight.
