### ISSUE TITLE
Passing cLEDMatrix object reference

### ISSUE THREAD

**Issue by rvecchio** [AaronLiddiment/LEDMatrix#17]
Hi,
I cannot find a way to pass an existing cLEDMatrix reference (that has been created outside) into a class (e.g. in the CTor) and use it inside the class.
I tried to pass the reference of the base class cLEDMatrixBase, but then nothing works (leds are not available, sprites cannot be created, etc.)

My class CTor is the following:
Foo(cLEDMatrixBase *matrix);

I have created the matrix in the main.ccp of the scketch like so:
cLEDMatrix<MATRIX_WIDTH, MATRIX_HEIGHT, MATRIX_TYPE> leds;

And I would like to pass the leds pointer to the Foo class CTor, but in this case I get a compiler error: 'cLEDMatrix' is not a type

Any hint on how to overcome this issue?
Thanks!

**Comment by AaronLiddiment** [comment]
It's a templated class for the reason that it only puts the required code in to deal with the particular matrix type. This makes resultant code more efficient and smaller.
In order to pass a pointer to it you must include the template params. I think using the following for you parameter definition instead of cLEDMatrixBase * should work.
cLEDMatrix<MATRIX_WIDTH, MATRIX_HEIGHT, MATRIX_TYPE> *

**Comment by rvecchio** [comment]
Thank you so much for your quick reply.
I could not make it work as you suggested, but I found another way.
I went back to the original idea of passing the led matrix reference as cLEDMatrixBase and it works.
I'm posting the Foo class that shows all the basic behaviors that I needed and it works.

#include <FastLED.h>
#include <LEDMatrix.h>
#include <LEDSprites.h>

const uint8_t RacketShapeData[] = 
{
    B8_1BIT(11110000),
};
struct CRGB SpritesColTable[1] = { CRGB(64, 128, 255) };

class Foo {
  private:
    cLEDMatrixBase *m_Matrix;
    cLEDSprites *m_Sprites;
    cSprite *m_RacketShape;

  public:
    Foo(cLEDMatrixBase *Matrix) {
        m_Matrix = Matrix;

        cLEDSprites Sprites(m_Matrix);
        m_Sprites = &Sprites;

        cSprite RacketShape(4, 1, RacketShapeData, 1, _1BIT, SpritesColTable, RacketShapeData);
        m_RacketShape = &RacketShape;

        setGame();
    }

    void setGame() {
        m_RacketShape->SetPositionFrameMotionOptions(m_Matrix->Width() /2/*X*/, m_Matrix->Height() / 2/*Y*/, 0/*Frame*/, 0/*FrameRate*/, 0/*XChange*/, 1/*XRate*/, 0/*YChange*/, 0/*YRate*/, SPRITE_DETECT_EDGE | SPRITE_DETECT_COLLISION);
        m_Sprites->AddSprite(m_RacketShape);

        FastLED.clear();
        m_Sprites->UpdateSprites();
        m_Sprites->RenderSprites();


        // this is to set a signle LED through cLEDMatrixBase
        m_Matrix->operator()(40) = CRGB::Red;

        FastLED.show();
    }
};

From the main.cpp, I can create the Foo object as follows:
Foo foo(&leds);
