### ISSUE TITLE
Access to FastLED CRGB object

### ISSUE THREAD

**Issue by ChrisLaurie** [AaronLiddiment/LEDMatrix#3]
Cannot find the appropriate forum to ask this question, but maybe it is just something that can be documented in the Wiki, but most probably my lack of C++ knowledge. The fastLED library has some utility procedures that require a CRGB object passed into it as a parameter. e.g. nscale8 and rainbow However I cannot seem to isolate the CRGB object to pass into these procedures. If I pass the leds object I get an error.

So Id like to know how would I call the fastLED procedure from within a sketch that uses LEDMatrix.

void fill_rainbow( struct CRGB \* pFirstLED, int numToFill,
                  uint8_t initialhue,
                  uint8_t deltahue )

What do I pass into this procedure for instance

**Comment by AaronLiddiment** [comment]
Hi,
It is kind of answered in the Wiki:-
https://github.com/AaronLiddiment/LEDMatrix/wiki/2.Usage
but it isn't explicitly stated. But the last line shows - *(leds[i]) = CRGB::White;
So leds[index] is actually the address of the LED at index.
Hope this sorts out your problem.

**Comment by ChrisLaurie** [comment]
Thanks for the answer Aaron! But it is not quite it (or I don't understand). Your example shows me how to access a single pixel, and I have that in my code. My confusion is the how to access CRGB array of FastLED as a single object. 

Using my example above. Under normal FastLED use the call would look like this:

fill_rainbow( leds, NUM_LEDS, 25, 7);

How would I call the fill_rainbow function from inside an LEDMatix sketch?

**Comment by AaronLiddiment** [comment]
Sorry, I have been coding for years so pointers & arrays are second nature for me and I forget that we all have to learn ;)
In C an array is always stored sequentially in memory so if you have the address of the 1st element then you can access the whole array. So leds[0] gives the address of the first CRGB element therefore...
fill_rainbow(leds[0], NUM_LEDS, 25, 7);
Hope that explains it a bit better :)

**Comment by ChrisLaurie** [comment]
Ahh, I recall reading about this C way of handling arrays and thinking to
myself: "that looks a bit dangerous and difficult to follow, don't think
I'll be doing that". And now a perfectly correct use case. Thank you, I've
learned something.

**Comment by AaronLiddiment** [comment]
:)
Of course normally you would have to use the & to get the address but in my Matrix class I have overloaded the [] operators to do it differently.....
So normally : 
CRGB leds;
&leds[0]
And of course you can also just use the array name with no [] which also returns the address of the first element which is how your original fill_rainbow line worked.
