### ISSUE TITLE
DrawLine() exceptions when the starting point and end point are exactly the same.

### ISSUE THREAD

**Issue by joehui** [AaronLiddiment/LEDMatrix#5]
Tested this on ESP8266, it crashed because of division by zero on the line:

```
             int32_t f = ((int32_t)dy << 16) / (int32_t)abs(dx);
```

because both dx and dy are zero.

I corrected the code by adding a condition for when dx and dy are both zeros.  The first few lines of the function becomes:

```
void cLEDMatrixBase::DrawLine(int16_t x0, int16_t y0, int16_t x1, int16_t y1, CRGB Col)
{
  int16_t dx = x1 - x0;
  int16_t dy = y1 - y0;
  
  if (dx==0 && dy==0) {
  	(*this)(x0, y0) = Col;
  }
  else if (abs(dx) >= abs(dy))
  {
    ......
```

I hope you can put this fix in your official code.

**Comment by marcmerlin** [comment]
Funny, I found the same bug independently.
I wrote a fix here if that helps: https://github.com/Jorgen-VikingGod/LEDMatrix/pull/2

**Comment by marcmerlin** [comment]
@AaronLiddiment  I know you are not maintaining this library anymore, but would you mind merging any fix to stop this division by 0 bug that is biting any user I point at your lib?
Thankfully Jorgen just merged my fix, but some people use your lib directly instead of his extended version.
Thanks.

**Comment by AaronLiddiment** [comment]
ok, fixed, closed.

**Comment by marcmerlin** [comment]
much appreciated, thank you.
