### ISSUE TITLE
Change strip connection layout

### ISSUE THREAD

**Issue by AlirezaAbdiyan** [AaronLiddiment/LEDMatrix#6]
Hi,
Are your library has a setting to connect pixel like this:
    0 > 1 >  2  >  3  >  4
                                    |
    ----<----<----<-----
    |
    5 >  6 >  7 >  8 >  9
                                   |
    ----<----<----<----
    |
   10 > 11 > 12 > 13 > 14

the end of pixel connect to begin of next strip.
Thanks a lot.

**Comment by AaronLiddiment** [comment]
Yes, just use HORIZONTAL_MATRIX for the type and use a negative height if you want the Y0 to be at the bottom instead of the top e.g.
cLEDMatrix<MATRIX_WIDTH, -MATRIX_HEIGHT, HORIZONTAL_MATRIX> leds;

**Comment by AlirezaAbdiyan** [comment]
Thanks
