### ISSUE TITLE
Color Math not working anymore

### ISSUE THREAD

**Issue by bombcheck** [AaronLiddiment/LEDMatrix#8]
Tried to implement your great work into one of my projects. Doing some effects with FastLED there and now would like to have scrolling text as well. But my effects are using the FastLED color math, which is broken when using your lib.

For example I use this in my code:
`leds[pos] += CHSV(gHue, 255, 100);`

When setting up to use your lib, I get a compile error:
`no match for 'operator+=' (operand types are 'CRGB*' and 'CRGB'`

Any idea how to solve this?

**Comment by AaronLiddiment** [comment]
This is an easy one ;)
Using [pos] is the address of the CRGB
Using (pos) is the actual CRGB
Let me know if this solves your problem.

**Comment by bombcheck** [comment]
Great! That did the trick I think!

**Comment by bombcheck** [comment]
But how can I build the text array at runtime? Trying without "const" it gaves me weird output...

**Comment by AaronLiddiment** [comment]
Are you declaring the text array inside a function?
The address of the array is stored when SetText() is called and is used when UpdateText() is called so if you declare the array inside a function it is allocated on the stack and will be deallocated at the end of the function.
You can use 'static' or declare the array outside of any function or you can allocate the memory but it is important to make sure it stays in the same place.

**Comment by bombcheck** [comment]
*facepalm* OK, got it. Thank you!!
